### ISSUE TITLE
Build fails on x86_64 

### ISSUE THREAD

**Issue by marcusthomas11** [iraf-community/x11iraf#37]
I am attempting to build the latest beta on macOS 11.1, which is x64 only. 
X11 libraries on this OS are installed to /opt/X11/ rather than /usr/X11, where the makefiles look for them, so I changed the makefiles to search for X11 in /opt/, and they were found. 

Though, I'm met with the following now when I try compile: 
<img width="658" alt="image" src="https://user-images.githubusercontent.com/77304991/104384140-92696200-54f6-11eb-9f25-ccf223655cc8.png">

Could this be from meddling with the X11 locations in the makefiles? 

I was able to compile and use this beta on another machine running 11.1, but am hitting a wall on this one. 

Thank you

**Comment by olebole** [comment]
This looks like you have somewhere an old version of Tcl in your search path.

**Comment by olebole** [comment]
Can this one be closed? Did you find the cause of the wong Tcl version?

**Comment by marcusthomas11** [comment]
I had something come up and had to stop testing— but I was not able to find
the issue.

I could not find where to point the compiler to a different installation of
tcl.

**Comment by olebole** [comment]
I must say that I do not fully understand this.
On macOSX, the version used is 8.5.9; and then these two functions are implemented locally: https://github.com/iraf-community/x11iraf/blob/77ff4029188eacf43b85e65331ff9724665d2283/obm/Obm.c#L101-L120

which means that they are actually defined. So, the only reason I could imagine is that another `tcl.h` include file was used (from an Tcl 8.6), but it is linked to the original tcl 8.5. This is where you start to debug (I can't do more here).

Since you mention that this was a beta release of macOSX: maybe you upgrade to the final version? Beta versions tend to have problems.

**Comment by marcusthomas11** [comment]
You were correct. It was pointing to Tcl 8.6 rather than 8.5.x. Thank you.
