### ISSUE TITLE
Error during "make" of x11iraf

### ISSUE THREAD

**Issue by Lokhamb** [iraf-community/x11iraf#47]
When I entered "make" in the terminal, I got the following errors...
```
make -C xgterm
make[1]: Entering directory '/iraf/x11iraf/x11iraf-main/xgterm'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/iraf/x11iraf/x11iraf-main/xgterm'
make -C ximtool
make[1]: Entering directory '/iraf/x11iraf/x11iraf-main/ximtool'
cd clients && mkpkg || true
Warning, hlib$mkpkg.inc line 5: macro 'IRAFARCH' not found
Subdirectory lib is up to date
Subdirectory wcspix is up to date
Library libpkg.a is up to date
Object x_ism.o is up to date
xc -Nz   -z x_ism.o libpkg.a -o ism_wcspix.e -lds -lxtools -liminterp -lslalib
gcc: error: libcfitsio.a: No such file or directory
Warning, mkpkg line 3: module 'relink' not found or returned error
make[1]: Leaving directory '/iraf/x11iraf/x11iraf-main/ximtool'
```

How to overcome this, Thank You...

**Comment by olebole** [comment]
This happens when you use the "old" installation of NOAO IRAF to build the module in x11iraf and don't provide the corresponding libcfitsio.a at the place where the old version expects it. If you use the old xc, you should also set the `iraf` and `IRAFARCH` environment variables accordingly.
The best way is to switch to the new IRAF version. And if you use a (recent version of) Debian, Ubuntu, or Mint, you can use x11iraf (xgterm and ximtool packages) directly from the distribution.
If you just need xgterm, you can also choose to ignore this, since xgterm is already built at this stage. The error appears only when it builds an additional module to display wcs coordinates in ximtool. If you use DS9, this is not required at all.

**Comment by olebole** [comment]
Did this resolve your problem? If yes, the issue could be closed.
